# Generated by Django 2.2 on 2022-10-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone_num',
            name='nick_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
